swagger: "2.0"
info:
  description: Swagger for CRUD operations
  version: "1.0.0"
  title: CRUD operations
consumes:
  - application/json
produces:
  - application/json

basePath: /aiops

# Paths supported by the server application
paths:
  /student/add_data:
    post:
      tags:
      - "STUDENT"
      summary: "insert operation"
      description: "insert operation"
      operationId: assignment.insert_student  #method name in the main file
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
        - name: name
          in: formData
          type: string
          required: True
        - name: class_id
          in: formData
          type: integer
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string

  /student/info:
    get:
      tags:
        - "STUDENT"
      summary: "read opearation"
      description: "read opearation"
      operationId: assignment.read_student
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string

  /student/edit:
    put:
      tags:
        - "STUDENT"
      summary: "update opearation"
      description: "update opearation"
      operationId: assignment.update_student
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
        - name: name
          in: formData
          type: string
          required: True
        - name: class_id
          in: formData
          type: integer
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string

  /student/remove:
    delete:
      tags:
        - "STUDENT"
      summary: "delete opearation"
      description: "delete opearation"
      operationId: assignment.delete_student
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string

  /class/add_data:
    post:
      tags:
        - "CLASS"
      summary: "insert operation"
      description: "insert operation"
      operationId: assignment.insert_class  #method name in the main file
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
        - name: name
          in: formData
          type: string
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string

  /class/info:
    get:
      tags:
        - "CLASS"
      summary: "read opearation"
      description: "read opearation"
      operationId: assignment.read_class
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string
  /class/edit:
    put:
      tags:
        - "CLASS"
      summary: "update opearation"
      description: "update opearation"
      operationId: assignment.update_class
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
        - name: name
          in: formData
          type: string
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string

  /class/remove:
    delete:
      tags:
        - "CLASS"
      summary: "delete opearation"
      description: "delete opearation"
      operationId: assignment.delete_class
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string